# Generated by Django 5.2.4 on 2025-07-27 20:03

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False),
        ),
    ]
