# Generated by Django 5.2.4 on 2025-08-07 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_booked',
            new_name='is_blocked',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be entered in the format: '01xxxxxxxxx' and By default it should be 11 digits long.", regex='^01\\d{9}$')], verbose_name='Mobile Number'),
        ),
    ]
