# Generated by Django 5.2.4 on 2025-08-11 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate_name_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('governorate_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governorates', to='locations.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.governorate'),
            preserve_default=False,
        ),
    ]
