# Generated by Django 5.2.4 on 2025-08-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_city_country_governorate_city_governorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governorate',
            name='governorate_name_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
