# Generated by Django 5.2.4 on 2025-08-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_governorate_governorate_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name_en',
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
